
on:
  push:
    branches:
      - master
      - chore-github-actions  # TODO: Remove before merging

name: publish

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build validator-web image
        run: |
          docker build \
            --no-cache \
            --tag ghcr.io/spaceapi/validator-web:latest \
            --label "org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            .
      - name: Publish validator-web image
        run: |
          docker push -a ghcr.io/spaceapi/validator-web
